### ISSUE TITLE
Lack of CI-based testing

### ISSUE THREAD

**Issue by xtrasimplicity** [cucumber/cucumber-lua#11]
Hi all,

I've just noticed that there isn't any continuous integration testing for this repository.

It would be great to have something like this, so that we can ensure that all tests pass prior to merging PRs.

I'm happy to take a look at getting the foundations of this going, though I admit I haven't used lua in close to 15 years. @olleolleolle or @mvz, would either of you be able to enable this repo in the Cucumber Travis CI or Circle CI account, if it hasn't already been done so?

Thanks!

**Comment by mvz** [comment]
I'll take a look.

**Comment by mvz** [comment]
@xtrasimplicity done!

**Comment by xtrasimplicity** [comment]
Brilliant, thanks @mvz!

**Comment by olleolleolle** [comment]
This got done _real quick_, thanks all.

**Comment by xtrasimplicity** [comment]
Not a problem. [hererocks](https://github.com/mpeterv/hererocks) made this heaps easier, as they have a Travis CI template. All it needed was a little trial and error with the allowed_failures section. :)
